import type { Metadata } from "next";
import { UserProvider } from "../contexts/UserContext";
import { GroupProvider } from "../contexts/GroupContext";
import { Inter } from "next/font/google";
import { Navbar } from "../components/navbar";
import { Footer } from "../components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <UserProvider>
      <GroupProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <div className="flex-grow overflow-auto pl-72">{children}</div>
              <Footer className="mt-auto" />
            </div>
          </body>
        </html>
      </GroupProvider>
    </UserProvider>
  );
};

export default RootLayout;
